# Generated by Django 5.0.6 on 2024-07-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='файл'),
        ),
    ]
