# Generated by Django 5.0.7 on 2024-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfacts', '0002_category_slug_song_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='файл'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='cat',
        ),
        migrations.AddField(
            model_name='song',
            name='cat',
            field=models.ManyToManyField(to='funfacts.category'),
        ),
    ]
