# Generated by Django 5.0.7 on 2024-07-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfacts', '0004_alter_song_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funfacts.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cat',
            field=models.ManyToManyField(related_name='category', to='funfacts.category', verbose_name='Жанры (Можешь выбрать несколько, разраб постарался)'),
        ),
    ]
